"""Deterministic body metrics for the fitness module.

Everything a number could hurt someone with lives here, and none of it is
generated by a model: BMI, BMR, maintenance calories, the calorie target,
macros and the guardrails around them. The LLM writes the plan *around*
these figures and is never allowed to pick them – the same principle as
the safety layer putting a deterministic tier in front of the chat model.

Pure functions, no I/O, so all of it is unit-tested directly.
"""

from __future__ import annotations

import math
from typing import Any

ACTIVITY_FACTORS: dict[str, float] = {
    "sedentary": 1.2,     # desk job, little or no exercise
    "light": 1.375,       # light exercise 1-3 days/week
    "moderate": 1.55,     # moderate exercise 3-5 days/week
    "active": 1.725,      # hard exercise 6-7 days/week
    "very_active": 1.9,   # physical job or twice-a-day training
}

ACTIVITY_LABELS: dict[str, str] = {
    "sedentary": "Sedentary",
    "light": "Lightly active",
    "moderate": "Moderately active",
    "active": "Very active",
    "very_active": "Extremely active",
}

GOAL_LABELS: dict[str, str] = {
    "lose": "Lose fat",
    "maintain": "Maintain weight",
    "gain": "Build muscle",
    "fitness": "Improve overall fitness",
}

# Absolute daily floors. A plan below these needs medical supervision, not
# an app, so the calculator simply refuses to go lower.
CALORIE_FLOOR = {"male": 1500, "female": 1200, "other": 1350}

# (upper bound exclusive, key, label, colour)
_WHO_BANDS = [
    (16.0, "underweight", "Severely underweight", "#3b82f6"),
    (18.5, "underweight", "Underweight", "#38bdf8"),
    (25.0, "normal", "Healthy weight", "#10b981"),
    (30.0, "overweight", "Overweight", "#f59e0b"),
    (35.0, "obese", "Obese (Class I)", "#f97316"),
    (40.0, "obese", "Obese (Class II)", "#ef4444"),
    (math.inf, "obese", "Obese (Class III)", "#dc2626"),
]

# WHO expert consultation (2004) / Indian consensus guidelines (2009):
# South Asian populations carry more metabolic risk at a lower BMI, so the
# overweight and obese thresholds sit lower.
_ASIAN_BANDS = [
    (16.0, "underweight", "Severely underweight", "#3b82f6"),
    (18.5, "underweight", "Underweight", "#38bdf8"),
    (23.0, "normal", "Healthy weight", "#10b981"),
    (25.0, "overweight", "Overweight", "#f59e0b"),
    (30.0, "obese", "Obese (Class I)", "#f97316"),
    (math.inf, "obese", "Obese (Class II)", "#ef4444"),
]

_HEALTHY_RANGE = {"who": (18.5, 24.9), "asian": (18.5, 22.9)}


def _round_to(value: float, step: int) -> int:
    return int(step * round(value / step))


def bmi(weight_kg: float, height_cm: float) -> float:
    if weight_kg <= 0 or height_cm <= 0:
        raise ValueError("weight and height must be positive")
    metres = height_cm / 100
    return round(weight_kg / (metres * metres), 1)


def bmi_category(value: float, standard: str = "asian") -> dict[str, str]:
    bands = _ASIAN_BANDS if standard == "asian" else _WHO_BANDS
    for upper, key, label, colour in bands:
        if value < upper:
            return {"key": key, "label": label, "color": colour}
    return {"key": "obese", "label": "Obese", "color": "#dc2626"}  # pragma: no cover


def healthy_weight_range(height_cm: float, standard: str = "asian") -> tuple[float, float]:
    low, high = _HEALTHY_RANGE.get(standard, _HEALTHY_RANGE["who"])
    metres_sq = (height_cm / 100) ** 2
    return round(low * metres_sq, 1), round(high * metres_sq, 1)


def bmr(weight_kg: float, height_cm: float, age: int, sex: str) -> int:
    """Mifflin-St Jeor. The most accurate simple equation for adults."""
    base = 10 * weight_kg + 6.25 * height_cm - 5 * age
    offset = {"male": 5, "female": -161}.get(sex, -78)  # "other": midpoint
    return round(base + offset)


def tdee(bmr_value: float, activity_level: str) -> int:
    return round(bmr_value * ACTIVITY_FACTORS.get(activity_level, 1.2))


def body_fat_estimate(bmi_value: float, age: int, sex: str) -> float | None:
    """Deurenberg (1991). A population estimate, shown as such. Not
    meaningful for under-18s, so it is withheld for them."""
    if age < 18:
        return None
    sex_term = {"male": 1.0, "female": 0.0}.get(sex, 0.5)
    value = 1.20 * bmi_value + 0.23 * age - 10.8 * sex_term - 5.4
    return round(max(value, 3.0), 1)


def water_litres(weight_kg: float, activity_level: str) -> float:
    base = weight_kg * 0.035
    if activity_level in {"active", "very_active"}:
        base += 0.5
    elif activity_level == "moderate":
        base += 0.25
    return round(min(max(base, 1.5), 5.0), 1)


def effective_goal(goal: str, bmi_value: float, age: int) -> tuple[str, list[str]]:
    """Apply guardrails to the requested goal. Returns (goal, notes)."""
    notes: list[str] = []
    if goal == "lose" and bmi_value < 18.5:
        notes.append(
            "Your BMI is already below the healthy range, so MindWell won't "
            "build a fat-loss plan. Your plan focuses on strength and "
            "nourishing, regular meals instead. If losing weight still feels "
            "important to you, a doctor or dietitian is the right person to "
            "talk it through with."
        )
        return "gain", notes
    if goal == "lose" and age < 18:
        notes.append(
            "You're still growing, so your plan keeps calories at "
            "maintenance and uses activity, not eating less, to improve "
            "body composition."
        )
        return "maintain", notes
    if bmi_value < 18.5 and goal == "maintain":
        notes.append(
            "Your BMI is below the healthy range. A small calorie surplus "
            "alongside strength training is usually recommended – worth "
            "discussing with a doctor."
        )
    return goal, notes


def calorie_target(
    tdee_value: int, bmr_value: int, goal: str, sex: str
) -> tuple[int, int]:
    """Returns (target_calories, daily_adjustment)."""
    if goal == "lose":
        adjustment = -min(500, round(tdee_value * 0.20))
    elif goal == "gain":
        adjustment = min(350, round(tdee_value * 0.12))
    else:
        adjustment = 0

    target = tdee_value + adjustment
    floor = max(CALORIE_FLOOR.get(sex, 1350), bmr_value)
    if goal == "lose" and target < floor:
        target = min(floor, tdee_value)
        adjustment = target - tdee_value
    return _round_to(target, 10), _round_to(adjustment, 10)


def macros(
    calories: int, weight_kg: float, height_cm: float, goal: str, bmi_value: float
) -> dict[str, int]:
    """Protein by bodyweight, fat as a share of calories, carbs the rest.

    For BMI above 30 protein is scaled to the weight at BMI 25 rather than
    total weight – otherwise the target becomes an unrealistic number.
    """
    per_kg = {"lose": 1.6, "gain": 1.6, "fitness": 1.4}.get(goal, 1.2)
    ref_weight = weight_kg
    if bmi_value > 30:
        ref_weight = 25 * (height_cm / 100) ** 2
    protein_g = round(ref_weight * per_kg)
    fat_g = round(calories * 0.27 / 9)
    carbs_kcal = calories - protein_g * 4 - fat_g * 9
    carbs_g = max(round(carbs_kcal / 4), 50)
    fibre_g = max(25, round(calories / 1000 * 14))
    return {
        "protein_g": protein_g,
        "carbs_g": carbs_g,
        "fat_g": fat_g,
        "fiber_g": fibre_g,
    }


def weekly_rate_kg(adjustment: int) -> float:
    """~7700 kcal per kg of body mass."""
    return round(adjustment * 7 / 7700, 2)


def compute_metrics(profile: dict[str, Any]) -> dict[str, Any]:
    weight = float(profile["weight_kg"])
    height = float(profile["height_cm"])
    age = int(profile["age"])
    sex = profile.get("sex", "other")
    activity = profile.get("activity_level", "sedentary")
    standard = profile.get("bmi_standard", "asian")

    bmi_value = bmi(weight, height)
    category = bmi_category(bmi_value, standard)
    low, high = healthy_weight_range(height, standard)
    bmr_value = bmr(weight, height, age, sex)
    tdee_value = tdee(bmr_value, activity)
    goal, notes = effective_goal(profile.get("goal", "maintain"), bmi_value, age)
    target, adjustment = calorie_target(tdee_value, bmr_value, goal, sex)

    if age < 18:
        notes.append(
            "For under-18s, BMI is properly read against growth percentiles, "
            "so treat the category as a rough guide."
        )
    if bmi_value >= 30:
        notes.append(
            "Consider a check-up before starting a new training plan – "
            "a doctor can clear you for exercise and check blood pressure "
            "and blood sugar."
        )

    if weight < low:
        to_range = round(low - weight, 1)
    elif weight > high:
        to_range = round(high - weight, 1)
    else:
        to_range = 0.0

    return {
        "bmi": bmi_value,
        "bmi_category": category["label"],
        "bmi_key": category["key"],
        "bmi_color": category["color"],
        "bmi_standard": standard,
        "healthy_weight_min": low,
        "healthy_weight_max": high,
        "kg_to_healthy_range": to_range,
        "bmr": bmr_value,
        "tdee": tdee_value,
        "target_calories": target,
        "calorie_adjustment": adjustment,
        "weekly_change_kg": weekly_rate_kg(adjustment),
        "macros": macros(target, weight, height, goal, bmi_value),
        "water_l": water_litres(weight, activity),
        "body_fat_pct": body_fat_estimate(bmi_value, age, sex),
        "requested_goal": profile.get("goal", "maintain"),
        "effective_goal": goal,
        "goal_label": GOAL_LABELS.get(goal, goal),
        "activity_label": ACTIVITY_LABELS.get(activity, activity),
        "guardrails": notes,
    }


# MET values (Compendium of Physical Activities, 2011), by category/intensity.
_METS = {
    "strength": {"low": 3.5, "moderate": 5.0, "high": 6.0},
    "cardio": {"low": 4.0, "moderate": 7.0, "high": 9.5},
    "hiit": {"low": 6.0, "moderate": 8.0, "high": 10.0},
    "yoga": {"low": 2.5, "moderate": 3.0, "high": 4.0},
    "walk": {"low": 2.8, "moderate": 3.5, "high": 5.0},
    "sports": {"low": 4.5, "moderate": 6.5, "high": 8.5},
    "other": {"low": 3.0, "moderate": 4.5, "high": 6.5},
}


def calories_burned(category: str, intensity: str, minutes: int, weight_kg: float) -> int:
    met = _METS.get(category, _METS["other"]).get(intensity, 4.5)
    return round(met * weight_kg * minutes / 60)


def activity_minutes_credit(intensity: str, minutes: int) -> int:
    """WHO: 150 min moderate or 75 min vigorous per week. Vigorous counts
    double so both land on the same 150-minute scale."""
    return minutes * 2 if intensity == "high" else minutes
